### PR TITLE
Adjust annotation output based on severity level

### PR DESCRIPTION
**Pull request by jlndk**
Hi @jamesacarr.

Thanks for making this package!
We, at [FirmNav](https://github.com/firmnav), are transitioning away from our own internal eslint formatter, and thought yours looks like a good replacement!
While transitioning we however noticed warnings were being reported as errors.
This PR is an attempt to rectify that. If anything should be changed, please don't hesitate to say so.

### CODE REVIEW

**Comment by jamesacarr** [comment]
Thanks for submitting this PR @jlndk!

Looks pretty solid to me.

**Comment by jamesacarr** [comment]
Only one request: change the commit message to follow the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines)? So something like `feat: Adjust annotation output based on severity level`

(Sorry, I haven't got around to adding that to the linting yet)

**Comment by jamesacarr** [comment]
Just a heads up that this was published as `0.1.0`

**Comment by jlndk** [comment]
Thanks for the fast response!

**Pull request merged**
